# Generated by Django 5.0.1 on 2025-12-31 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Data e ora di creazione automatica",
                        verbose_name="creato il",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e ora ultimo aggiornamento",
                        verbose_name="aggiornato il",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="nome completo"),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefono"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("adoption", "Richiesta adozione"),
                            ("info", "Richiesta informazioni"),
                            ("volunteer", "Volontariato"),
                            ("donation", "Donazioni"),
                            ("other", "Altro"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="oggetto",
                    ),
                ),
                ("message", models.TextField(verbose_name="messaggio")),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="letto"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Note dello staff (non visibili al mittente)",
                        verbose_name="note interne",
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_messages",
                        to="dogs.dog",
                        verbose_name="cane di interesse",
                    ),
                ),
            ],
            options={
                "verbose_name": "messaggio di contatto",
                "verbose_name_plural": "messaggi di contatto",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_read", "-created_at"],
                        name="contacts_co_is_read_c64a50_idx",
                    )
                ],
            },
        ),
    ]
