# Generated by Django 5.0.1 on 2026-01-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
        (
            "dogs",
            "0002_rename_dogs_dog_status_ee9c91_idx_dog_status_created_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                db_index=True,
                help_text="IP del mittente per sicurezza",
                null=True,
                verbose_name="indirizzo IP",
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="is_spam",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="contrassegnato come spam"
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="spam_score",
            field=models.FloatField(
                default=0.0,
                help_text="Score da reCAPTCHA (0=bot, 1=umano)",
                verbose_name="punteggio spam",
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="user_agent",
            field=models.CharField(
                blank=True,
                help_text="Browser/dispositivo utilizzato",
                max_length=500,
                verbose_name="user agent",
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["ip_address", "-created_at"],
                name="contacts_co_ip_addr_dde73f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contactmessage",
            index=models.Index(
                fields=["is_spam", "-created_at"], name="contacts_co_is_spam_148bd1_idx"
            ),
        ),
    ]
