# Generated by Django 5.0.1 on 2025-12-31 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Data e ora di creazione automatica",
                        verbose_name="creato il",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e ora ultimo aggiornamento",
                        verbose_name="aggiornato il",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="nome categoria"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordine di visualizzazione",
                        verbose_name="ordine",
                    ),
                ),
            ],
            options={
                "verbose_name": "categoria FAQ",
                "verbose_name_plural": "categorie FAQ",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Data e ora di creazione automatica",
                        verbose_name="creato il",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e ora ultimo aggiornamento",
                        verbose_name="aggiornato il",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Spunta per rendere visibile sul sito",
                        verbose_name="pubblicato",
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="domanda")),
                ("answer", models.TextField(verbose_name="risposta")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordine di visualizzazione",
                        verbose_name="ordine",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faqs",
                        to="faq.faqcategory",
                        verbose_name="categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQ",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
