# Generated by Django 5.0.1 on 2025-12-31 20:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Data e ora di creazione automatica",
                        verbose_name="creato il",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e ora ultimo aggiornamento",
                        verbose_name="aggiornato il",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="nome razza",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descrizione delle caratteristiche della razza",
                        verbose_name="descrizione",
                    ),
                ),
            ],
            options={
                "verbose_name": "razza",
                "verbose_name_plural": "razze",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Data e ora di creazione automatica",
                        verbose_name="creato il",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e ora ultimo aggiornamento",
                        verbose_name="aggiornato il",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Spunta per rendere visibile sul sito",
                        verbose_name="pubblicato",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Nome del cane",
                        max_length=100,
                        verbose_name="nome",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Generato automaticamente dal nome",
                        max_length=120,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "microchip_number",
                    models.CharField(
                        blank=True,
                        help_text="Codice identificativo microchip",
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="numero microchip",
                    ),
                ),
                (
                    "is_mixed_breed",
                    models.BooleanField(
                        default=False,
                        help_text="Spunta se è un meticcio",
                        verbose_name="meticcio",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Maschio"), ("F", "Femmina")],
                        db_index=True,
                        max_length=1,
                        verbose_name="sesso",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("XS", "Mini (< 5kg)"),
                            ("S", "Piccola (5-10kg)"),
                            ("M", "Media (10-25kg)"),
                            ("L", "Grande (25-45kg)"),
                            ("XL", "Gigante (> 45kg)"),
                        ],
                        db_index=True,
                        max_length=2,
                        verbose_name="taglia",
                    ),
                ),
                (
                    "age_years",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(25),
                        ],
                        verbose_name="età (anni)",
                    ),
                ),
                (
                    "age_months",
                    models.IntegerField(
                        default=0,
                        help_text="Da 0 a 11 mesi",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(11),
                        ],
                        verbose_name="età (mesi)",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="peso (kg)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Storia e carattere del cane",
                        verbose_name="descrizione",
                    ),
                ),
                (
                    "special_needs",
                    models.TextField(
                        blank=True,
                        help_text="Diete, terapie o limitazioni particolari",
                        verbose_name="esigenze speciali",
                    ),
                ),
                (
                    "good_with_children",
                    models.BooleanField(default=False, verbose_name="adatto a bambini"),
                ),
                (
                    "good_with_dogs",
                    models.BooleanField(
                        default=False, verbose_name="adatto ad altri cani"
                    ),
                ),
                (
                    "good_with_cats",
                    models.BooleanField(default=False, verbose_name="adatto a gatti"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponibile"),
                            ("adopted", "Adottato"),
                            ("reserved", "Prenotato"),
                            ("medical", "In cura"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                        verbose_name="stato",
                    ),
                ),
                (
                    "arrival_date",
                    models.DateField(
                        db_index=True,
                        help_text="Quando è arrivato al canile",
                        verbose_name="data arrivo",
                    ),
                ),
                (
                    "adoption_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="data adozione"
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        help_text="Foto principale per la gallery",
                        null=True,
                        upload_to="dogs/main/%Y/%m/",
                        verbose_name="immagine principale",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="visualizzazioni"
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dogs",
                        to="dogs.breed",
                        verbose_name="razza",
                    ),
                ),
            ],
            options={
                "verbose_name": "cane",
                "verbose_name_plural": "cani",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Data e ora di creazione automatica",
                        verbose_name="creato il",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e ora ultimo aggiornamento",
                        verbose_name="aggiornato il",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="dogs/gallery/%Y/%m/", verbose_name="immagine"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="didascalia"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordine di visualizzazione",
                        verbose_name="ordine",
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="dogs.dog",
                        verbose_name="cane",
                    ),
                ),
            ],
            options={
                "verbose_name": "immagine cane",
                "verbose_name_plural": "immagini cani",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dog",
            index=models.Index(
                fields=["status", "-created_at"], name="dogs_dog_status_ee9c91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dog",
            index=models.Index(
                fields=["size", "gender"], name="dogs_dog_size_1785c8_idx"
            ),
        ),
    ]
