# Generated by Django 5.0.1 on 2026-01-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dog",
            new_name="dog_status_created_idx",
            old_name="dogs_dog_status_ee9c91_idx",
        ),
        migrations.RenameIndex(
            model_name="dog",
            new_name="dog_size_gender_idx",
            old_name="dogs_dog_size_1785c8_idx",
        ),
        migrations.AddIndex(
            model_name="dog",
            index=models.Index(fields=["-arrival_date"], name="dog_arrival_idx"),
        ),
        migrations.AddIndex(
            model_name="dog",
            index=models.Index(
                fields=["is_published", "status"], name="dog_published_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dog",
            index=models.Index(fields=["slug"], name="dog_slug_idx"),
        ),
    ]
