# Generated by Django 5.0.1 on 2026-04-22 17:18

import apps.dogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dogs",
            "0002_rename_dogs_dog_status_ee9c91_idx_dog_status_created_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dog",
            name="main_image",
            field=models.ImageField(
                blank=True,
                help_text="Foto principale per la gallery (jpg/png/webp, max 5 MB)",
                null=True,
                upload_to="dogs/main/%Y/%m/",
                validators=[apps.dogs.validators.validate_dog_image],
                verbose_name="immagine principale",
            ),
        ),
        migrations.AlterField(
            model_name="dogimage",
            name="image",
            field=models.ImageField(
                upload_to="dogs/gallery/%Y/%m/",
                validators=[apps.dogs.validators.validate_dog_image],
                verbose_name="immagine",
            ),
        ),
    ]
